# Generated by Django 3.1.5 on 2021-06-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('DateTime', models.CharField(max_length=40)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('DateTime', models.CharField(max_length=40)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('SemesterTarget', models.IntegerField(default=0, max_length=3)),
                ('OverallTarget', models.IntegerField(default=0, max_length=3)),
                ('YourPercentage_predicted', models.IntegerField(max_length=3)),
                ('OverallPercentage_predicted', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('Mid_1', models.IntegerField(max_length=3)),
                ('Mid_2', models.IntegerField(max_length=3)),
                ('External_1', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('BarChart', models.FileField(upload_to='barcharts/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('point1', models.CharField(max_length=150)),
                ('point2', models.CharField(max_length=150)),
                ('point3', models.CharField(max_length=150)),
                ('point4', models.CharField(max_length=150)),
                ('point5', models.CharField(max_length=150)),
                ('point6', models.CharField(max_length=150)),
                ('point7', models.CharField(max_length=150)),
                ('point8', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('PieChart', models.FileField(upload_to='piecharts/')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('sug1', models.CharField(max_length=150)),
                ('sug2', models.CharField(max_length=150)),
                ('sug3', models.CharField(max_length=150)),
                ('sug4', models.CharField(max_length=150)),
                ('sug5', models.CharField(max_length=150)),
            ],
        ),
    ]
