# Generated by Django 3.1.5 on 2021-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210610_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='OverallPercentage_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='YourPercentage_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='External_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mid_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mid_2',
            field=models.IntegerField(default=0),
        ),
    ]
