# Generated by Django 3.1.5 on 2021-06-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210610_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('S4', models.IntegerField(default=0)),
                ('S5', models.IntegerField(default=0)),
                ('S6', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mid_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('S4', models.IntegerField(default=0)),
                ('S5', models.IntegerField(default=0)),
                ('S6', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mid_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollnumber', models.CharField(max_length=10)),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('S4', models.IntegerField(default=0)),
                ('S5', models.IntegerField(default=0)),
                ('S6', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
