# Generated by Django 3.1.5 on 2021-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210611_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicactivities',
            name='Marks',
            field=models.IntegerField(default=0),
        ),
    ]
