# Generated by Django 3.1.5 on 2021-06-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_academicactivities_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivities',
            name='Marks',
            field=models.IntegerField(default=0),
        ),
    ]
